version: '3.8'

services:
  app:
    build: .
    network_mode: host
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/web/node_modules
      - /app/apps/api/node_modules
      - /app/apps/admin/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
