import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useMemo } from "react";
import { formatINR } from "../lib/format";
import { useApp } from "../context/AppContext";
export function CartDrawer() {
    const { cartDrawerOpen, setCartDrawerOpen, cart, changeCartQty, removeFromCart, isBootstrapping } = useApp();
    const hasItems = useMemo(() => (cart?.items.length ?? 0) > 0, [cart?.items.length]);
    return (_jsxs(_Fragment, { children: [_jsx("div", { className: `drawer-backdrop ${cartDrawerOpen ? "show" : ""}`, onClick: () => setCartDrawerOpen(false), role: "presentation" }), _jsxs("aside", { className: `cart-drawer ${cartDrawerOpen ? "open" : ""}`, "aria-label": "Cart Drawer", children: [_jsxs("header", { children: [_jsx("h3", { children: "Cart" }), _jsx("button", { type: "button", className: "icon-btn", onClick: () => setCartDrawerOpen(false), children: "\u2715" })] }), isBootstrapping ? (_jsxs("div", { className: "skeleton-list", children: [_jsx("div", { className: "skeleton h-72" }), _jsx("div", { className: "skeleton h-72" })] })) : !hasItems ? (_jsxs("div", { className: "empty-state compact", children: [_jsx("span", { children: "\uD83D\uDED2" }), _jsx("h4", { children: "Your cart is empty" }), _jsx("p", { children: "Add products from Udhikxa Luxe to see them here." })] })) : (_jsxs(_Fragment, { children: [_jsx("div", { className: "drawer-items", children: cart?.items.map((item) => (_jsxs("article", { className: "drawer-item", children: [_jsx("div", { className: "emoji", children: item.product.imageEmoji }), _jsxs("div", { children: [_jsx("h4", { children: item.product.name }), _jsxs("p", { children: [item.size, " \u00B7 ", item.color] }), _jsx("strong", { children: formatINR(item.product.pricePaise) })] }), _jsxs("div", { className: "qty-stack", children: [_jsxs("div", { className: "qty-stepper", children: [_jsx("button", { type: "button", onClick: () => void changeCartQty(item.id, Math.max(1, item.quantity - 1)), children: "\u2212" }), _jsx("span", { children: item.quantity }), _jsx("button", { type: "button", onClick: () => void changeCartQty(item.id, Math.min(10, item.quantity + 1)), children: "+" })] }), _jsx("button", { type: "button", className: "link-btn", onClick: () => void removeFromCart(item.id), children: "Remove" })] })] }, item.id))) }), _jsxs("footer", { className: "drawer-footer", children: [_jsx("label", { htmlFor: "coupon", children: "Promo code" }), _jsxs("div", { className: "coupon-row", children: [_jsx("input", { id: "coupon", placeholder: "Enter code" }), _jsx("button", { type: "button", className: "btn-corp", children: "Apply" })] }), _jsxs("div", { className: "summary-grid", children: [_jsx("span", { children: "Subtotal" }), _jsx("strong", { children: formatINR(cart.summary.subtotalPaise) }), _jsx("span", { children: "Shipping" }), _jsx("strong", { children: formatINR(cart.summary.shippingPaise) }), _jsx("span", { children: "Tax" }), _jsx("strong", { children: formatINR(cart.summary.taxPaise) })] }), _jsxs("div", { className: "summary-total", children: [_jsx("span", { children: "Total" }), _jsx("strong", { children: formatINR(cart.summary.totalPaise) })] }), _jsx("button", { type: "button", className: "btn-gold full", children: "Checkout" })] })] }))] })] }));
}
